### ISSUE TITLE
Stack overflow when building

### ISSUE THREAD

**Issue by agubelu** [Sequal32/simconnect-rust#4]
Hi, I've encountered an stack overflow error when trying to build a project using the simconnect crate:

![2021-01-19 10_06_05](https://user-images.githubusercontent.com/1207202/105012321-52e2ce80-5a3e-11eb-9483-36be19379d6d.png)

I've tried in two different machines with the same result, running rustup 1.23.1 + rustc 1.48.0 and 1.49.0.

I have also tried generating a stack trace of the error with little success, I'd appreciate some help to find out what's going wrong exactly.

Thank you!

**Comment by Sequal32** [comment]
Hi, this was caused by a change in one of the dependencies. More specifically, the crate thread_local in the regex crate upgraded to 1.1.0.

https://github.com/Amanieu/thread_local-rs/issues/23

I’ll add a new entry in the Cargo.toml similar to what skia-bindings did to fix this https://github.com/rust-skia/rust-skia/commit/c44b7c67238a510ef8cc56d3372a1802824acba3

**Comment by agubelu** [comment]
Thanks!
